openapi: 3.0.3
info:
  title: Blog API
  description: |
    **Простое API блога** для изучения OpenAPI 3.0
    
    Включает все основные концепции:
    - Аутентификация JWT
    - CRUD операции с постами
    - Комментарии
    - Пагинация и фильтрация
    
  version: 1.0.0
  contact:
    name: Blog API Support
    email: support@blog.com
  license:
    name: MIT

servers:
  - url: http://localhost:4010
    description: Development
  - url: https://api.blog.com/{version}
    description: Production
    variables:
      version:
        default: v1
        enum: [v1, v2]

security:
  - BearerAuth: []

tags:
  - name: Аутентификация
    description: Управление аутентификацией
  - name: Пользователи
    description: Управление пользователями блога
  - name: Статьи
    description: Операции с публикациями
  - name: Комментарии
    description: Работа с комментариями
  - name: Категории
    description: Управление категориями статей

paths:
  /auth/login:
    $ref: './paths/auth.login.yaml'
  /users:
    $ref: './paths/users.yaml'
  /posts:
    $ref: './paths/posts.yaml'
  /posts/{postId}:
    $ref: './paths/posts.postId.yaml'
  /posts/{postId}/comments:
    $ref: './paths/posts.postId.comments.yaml'
  /status:
    $ref: './paths/status.yaml'
  /cart:
    $ref: './paths/cart.yaml'

components:
  securitySchemes:
    BearerAuth:
      $ref: './components/securitySchemes/BearerAuth.yaml'

  parameters:
    PostIdParam:
      $ref: './components/parameters/PostIdParam.yaml'
    PageParam:
      $ref: './components/parameters/PageParam.yaml'
    LimitParam:
      $ref: './components/parameters/LimitParam.yaml'

  headers:
    TotalCount:
      $ref: './components/headers/TotalCount.yaml'

  responses:
    ValidationError:
      $ref: './components/responses/ValidationError.yaml'
    UnauthorizedError:
      $ref: './components/responses/UnauthorizedError.yaml'
    NotFoundError:
      $ref: './components/responses/NotFoundError.yaml'
    NotFound:
      $ref: '#/components/responses/NotFoundError'

  schemas:
    LoginRequest:
      $ref: './components/schemas/LoginRequest.yaml'
    AuthResponse:
      $ref: './components/schemas/AuthResponse.yaml'
    User:
      $ref: './components/schemas/User.yaml'
    UserCreate:
      $ref: './components/schemas/UserCreate.yaml'
    Post:
      $ref: './components/schemas/Post.yaml'
    PostCreate:
      $ref: './components/schemas/PostCreate.yaml'
    PostUpdate:
      $ref: './components/schemas/PostUpdate.yaml'
    PostList:
      $ref: './components/schemas/PostList.yaml'
    Comment:
      $ref: './components/schemas/Comment.yaml'
    CommentCreate:
      $ref: './components/schemas/CommentCreate.yaml'
    Pagination:
      $ref: './components/schemas/Pagination.yaml'
    Error:
      $ref: './components/schemas/Error.yaml'
    ValidationError:
      $ref: './components/schemas/ValidationError.yaml'

externalDocs:
  description: Полная документация API блога
  url: https://docs.example.com/api/blog 