services:
  prism:
    image: stoplight/prism:latest
    command: >-
      mock -h 0.0.0.0 -p 4010 --cors --errors --dynamic /spec/${SPEC_PATH:-openapi/openapi.yaml}
    ports:
      - "${PRISM_PORT:-4010}:4010"
    volumes:
      - ./docs:/spec:ro
    restart: unless-stopped

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      SWAGGER_JSON: /spec/${SPEC_PATH:-openapi/openapi.yaml}
    ports:
      - "${SWAGGER_PORT:-8080}:8080"
    volumes:
      - ./docs:/spec:ro
    depends_on:
      - prism
    restart: unless-stopped

