openapi: 3.0.3
info:
  title: API
  version: 0.1.0
servers:
  - url: http://localhost:4010
paths:
  /test:
    get:
      summary: Test
      tags: [test]
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required: [id, title]
                  properties:
                    id:
                      type: string
                      description: Unique todo identifier
                    title:
                      type: string
                      description: Human readable title
